<div class="component-navigation">
	<a href="index.html">
		<!--(bake /src/inc/common/icon.inc icon="logo-facebook" class="navigation-logo")-->
	</a>

	<ul class="navigation-list">
		<!-- TODO best way to add is-active class statically. through a class? some sort of logic in grunt-bake? -->
		<li class="navigation-item is-active"><a href="content.html">Content</a></li>
		<li class="navigation-item"><a href="about.html">About</a></li>
		<li class="navigation-item"><a href="contact.html">Contact</a></li>
	</ul>
</div>