<footer class="component-footer">
	<div class="copyright">&copy; Copyright 2015</div>
	<div class="social-links">
		<a href="#" target="_blank">
			<!--(bake /src/inc/common/icon.inc icon="email" class="")-->
		</a>
		<a href="#" target="_blank">
			<!--(bake /src/inc/common/icon.inc icon="logo-linkedin" class="")-->
		</a>
		<a href="#" target="_blank">
			<!--(bake /src/inc/common/icon.inc icon="logo-github" class="")-->
		</a>
	</div>
</footer>