<div class="component-content-tile">
	<div class="content-tile-image-container">
		<img class="content-tile-image" src="{{image}}" />
	</div>

	<div class="content-tile-text-container">
		<div class="content-tile-heading">{{heading}}</div>
		<ul class="content-tile-details">
			<li class="content-tile-detail">{{detail1}}</li>
			<li class="content-tile-detail">{{detail2}}</li>
			<li class="content-tile-detail">{{detail3}}</li>
		<ul>
		<div class="content-tile-text">{{text}}</div>
		<a href="{{link}}" class="content-tile-link">
			Take action
			<!--(bake /src/inc/common/icon.inc icon="chevron" class="")-->
		</a>
	</div>
</div>