<footer class="component-footer">
	<div class="copyright">&copy; 2015</div>
	<div class="social-links">
		<a href="#">
			<!--(bake /src/inc/common/icon.inc icon="logo-facebook" class="")-->
		</a>
		<a href="#">
			<!--(bake /src/inc/common/icon.inc icon="logo-linkedin" class="")-->
		</a>
		<a href="#">
			<!--(bake /src/inc/common/icon.inc icon="logo-twitter" class="")-->
		</a>
	</div>
</footer>